### ISSUE TITLE
We ran into a SystemStackError error on production

### ISSUE THREAD

**Issue by skatkov** [httprb/content_type.rb#5]
Just FYI, I've tried to use this gem on production yeat ran into a SystemStackError that brough down production for couple of hours. I was unable to reproduce this error locally, but managed to fish our error from logs:

```
/usr/local/bundle/gems/content-type-0.0.1/lib/content_type/parser.rb:30:in `to_s': stack level too deep (SystemStackError)
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet/atoms/str.rb:13:in `escape'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet/atoms/str.rb:13:in `initialize'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet.rb:157:in `new'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet.rb:157:in `str'
  from /usr/local/bundle/gems/content-type-0.0.1/lib/content_type/parser.rb:64:in `block in <class:Parser>'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet.rb:110:in `instance_eval'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet.rb:110:in `block (2 levels) in rule'
  from /usr/local/bundle/gems/parslet-1.8.2/lib/parslet/atoms/entity.rb:28:in `parslet'
 ... 10188 levels...
  from /usr/local/bundle/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  from /usr/local/bundle/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
  from /usr/local/bundle/bin/bundle:23:in `load'
  from /usr/local/bundle/bin/bundle:23:in `<main>'
  ```

**Comment by ixti** [comment]
@skatkov sorry to hear that. I will figure out the reason and fix it ASAP.
